# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pip-python-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        packageDirectory: ["ml_wrappers"]
        python-version: [3.6, 3.7, 3.8, 3.9, '3.10']
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }} ${{ matrix.os }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Upgrade pip
      run: |
        python -m pip install --upgrade pip
    - name: Install package
      run: |
        pip install -e ./python
    - name: Test with pytest
      run: |
        # pytest
        pip install pytest
        pytest .tests/ -s -v
